- name: Delete existing dist folder
  file:
    path: "{{ deployment_directory_path }}"
    state: absent

- name: Copy source files to remote host
  synchronize:
    src: "{{ deployment_directory_source }}"
    dest: "{{ deployment_directory_path }}"

- name: Create and start services
  docker_compose:
    project_src: "{{ deployment_directory_path }}"
    build: yes
  register: output