---

- include_vars:
    file: templates/things-board-rule-chain.json
    name: rule_chain_body

- name: Get thingsboard authentication token
  uri:
    url: "https://{{ HOST }}/api/auth/login"
    body:
      username: "{{ THINGSBOARD_USER }}"
      password: "{{ THINGSBOARD_PASSWORD }}"
    body_format: json
    status_code: 200
    method: POST
    return_content: yes
  register: access_token
  failed_when: "'token' not in access_token.json"

- name: Set access token as variable
  set_fact:
    auth_token: "Bearer {{ access_token.json.token }}"

- name: Get root rule chain
  uri:
    url: "https://{{ HOST }}/api/ruleChains?limit=10"
    body_format: json
    return_content: yes
    status_code: [200]
    headers:
      X-Authorization: "{{ auth_token }}"
  register: root_rule_chain
  # failed_when: "'root' not in root_rule_chain.json"

- name: Log rule jain
  debug: 
    msg: "{{ root_rule_chain.json  }}"

- name: Extract root rule chain id
  set_fact: 
    root_rule_chain_id: "{{ root_rule_chain.json | json_query('data[?root==`true`].id.id | [0] ') }}"
    root_rule_chain_metadata: "{{ rule_chain_body | json_query('metadata') | combine({ 'ruleChainId': { 'entityType': 'RULE_CHAIN', 'id': '{{ root_rule_chain_id }}' } }) }}"

- name: "Print root rule chain metadata"
  debug: 
    msg: "{{ root_rule_chain_metadata }}"

- name: Update root rule chain metadata
  uri:
    url: "https://{{HOST}}/api/ruleChain/metadata"
    body: "{{ root_rule_chain_metadata }}"
    body_format: json
    method: POST
    return_content: yes
    status_code: [200]
    headers:
      X-Authorization: "{{ auth_token }}"