---
- include_vars:
    file: templates/things-board-rule-chain.json
    name: rule_chain_body

- name: Get thingsboard authentication token
  uri:
    url: "{{ HOST }}/api/auth/login"
    body:
      username: "{{ THINGSBOARD_USER }}"
      password: "{{ THINGSBOARD_PASSWORD }}"
    body_format: json
    status_code: [200]
    method: POST
    return_content: yes
  register: access_token
  until: access_token.status == 200
  retries: 30
  delay: 10

- name: Set access token as variable
  set_fact:
    auth_token: "Bearer {{ access_token.json.token }}"

# Creat the rule chain
- name: Get root rule chain
  uri:
    url: "{{ HOST }}/api/ruleChains?limit=10"
    body_format: json
    return_content: yes
    status_code: [200]
    headers:
      X-Authorization: "{{ auth_token }}"
  register: root_rule_chain
  until: root_rule_chain.status == 200
  retries: 3
  delay: 10


- name: Log rule jain
  debug: 
    msg: "{{ root_rule_chain.json  }}"

- name: Extract root rule chain id
  set_fact: 
    root_rule_chain_id: "{{ root_rule_chain.json | json_query('data[?root==`true`].id.id | [0] ') }}"
    root_rule_chain_metadata: "{{ rule_chain_body | json_query('metadata') | combine({ 'ruleChainId': { 'entityType': 'RULE_CHAIN', 'id': '{{ root_rule_chain_id }}' } }) }}"

- name: "Print root rule chain metadata"
  debug: 
    msg: "{{ root_rule_chain_metadata }}"

- name: Update root rule chain metadata
  uri:
    url: "{{HOST}}/api/ruleChain/metadata"
    body: "{{ root_rule_chain_metadata }}"
    body_format: json
    method: POST
    return_content: yes
    status_code: [200]
    headers:
      X-Authorization: "{{ auth_token }}"
  register: root_rule_chain_metadata_response
  until: root_rule_chain_metadata_response.status == 200
  retries: 3
  delay: 10
  
- name: Setup devices
  vars: 
    devices: 
    - name: Obstwaage
      type: waage
      token: obstwaage
      attributes:
        key: location
        value: Obstabteilung
    - name: Kassenbutton
      type: Checkstand-Button 
      token: kassenbutton
  include_tasks: setup_thingsboard_devices.yml
  loop: "{{ devices }}"
