# Generated by Django 3.0.8 on 2020-09-15 20:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=250, unique=True)),
                ('type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=250, unique=True)),
                ('lastname', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=250)),
            ],
        ),
    ]
