# Generated by Django 3.0.8 on 2020-07-20 21:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(verbose_name='date published')),
                ('fk_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Device')),
                ('fk_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Employee')),
            ],
        ),
    ]
